#!/bin/sh
# Copyright (C) 2014 Francois Gouget
#
# Asks a simple Yes/No question.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
name0=`basename "$0"`


error()
{
    echo "$name0:error:" "$@" >&2
}


#
# Command line processing
#

opt_msg=""
usage=""
while [ $# -gt 0 ]
do
    arg="$1"
    shift
    if [ "$arg" = "--help" -o "$arg" = "-h" -o "$arg" = "-?" ]
    then
        usage=0
        break
    elif [ -z "$opt_msg" ]
    then
        opt_msg="$arg"
    else
        error "unknown option '$arg'"
        usage=2
        break
    fi
done

if [ -z "$usage" ]
then
    if [ -z "$opt_msg" ]
    then
        error "you must provide the text of the question"
        usage=2
    fi
fi

if [ "$usage" = "0" ]
then
    echo "Usage: $name0 [--help] QUESTION"
    echo

    echo "Asks a simple Yes/No question to the user."
    echo

    echo "Where:"
    echo "  QUESTION     This is the text of the question. The answer will be Yes or No."
    echo "  --help, -h   Shows this help message."
    exit 0
elif [ -n "$usage" ]
then
    error "try '$name0 --help' for more information"
    exit $usage
fi


#
# Ask the question
#

if type osascript >/dev/null
then
    # This is Mac OS X but osascript provides no usable way of asking such a
    # question ('display dialog' is too buggy).
    exec python -c "from AppKit import NSAlert, NSApplication
NSApplication.sharedApplication().activateIgnoringOtherApps_(True)
res = NSAlert.alertWithMessageText_defaultButton_alternateButton_otherButton_informativeTextWithFormat_('$opt_msg', 'No', 'Yes', None, '').runModal()

import sys
sys.exit(res)"
else
    DISPLAY=:0.0 exec zenity --question --text "$opt_msg" 2>/dev/null
fi
