#!/bin/sh
# Copyright (C) 2020 Francois Gouget
#
# Installs the packages needed for Wine development.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
name0=`basename "$0"`


error()
{
    echo "$name0:error:" "$@" >&2
}

warning()
{
    echo "$name0:warning:" "$@" >&2
}

opt_dry_run=""

dry_run()
{
    local rc
    echo "$@"
    [ -z "$opt_dry_run" ] || return 0
    "$@"
    rc=$?
    [ $rc -ne 0 -a -n "$opt_dry_run" ] && echo " -> rc=$rc" >&2
    return $rc
}


#####
#
# Generic helpers
#
#####

pkginstall=""
pkgbroken=""
pkgmissing=""
pkgworkaround=""

wt_get_bad_pkgs()
{
    local pkg="$1"
    echo "$pkgbroken $pkgmissing" | tr ' ' '\n' | sort -u | egrep "^$pkg" | tr '\n' ' '
}

wt_remove_bad_pkg()
{
    local pkg="$1"
    pkgbroken=`echo "$pkgbroken " | sed -e "s/ $pkg[^ ]*/ /g"`
    pkgmissing=`echo "$pkgmissing " | sed -e "s/ $pkg[^ ]*/ /g"`
}

wt_explain_bad_pkg()
{
    local pkg="$1"
    if echo " $pkgmissing $pkgbroken " | grep -q " $pkg "
    then
        wt_remove_bad_pkg "$pkg"
        return 0
    fi
    return 1
}

wt_pretty_list()
{
    echo "$@" | tr ' ' '\n' | sort -u | tr '\n' ' ' | sed -e 's/^ //' -e 's/ $//'
}

wt_libdirs=""
wt_create_so_warn=1

# wt_create_so <sodev> <solib>
#
# Creates the <sodev>.so symlink pointing to the <solib>.so.<ver> library.
# If <solib> is omitted it is assumed to be identical to <sodev>.
# wt_create_so() also handles cases where the library is in /lib* rather than
# /usr/lib*.
#
# Returns 0 if the symlink was already present, 1 if it was successfully
# created, 2 if it could not be created.
wt_create_so()
{
    local libdir rc sover usrlibdir
    local sodev="$1"
    local solib="$2"
    [ -n "$solib" ] || solib="$sodev"
    if [ -z "$wt_libdirs" ]
    then
        error "the per-distribution code must set \$wt_libdirs"
        exit 1
    fi

    rc=0
    for libdir in $wt_libdirs
    do
        usrlibdir="/usr$libdir"
        if [ ! -f "$usrlibdir/$sodev.so" ]
        then
            sover=`cd "$usrlibdir" 2>/dev/null && ls "$solib.so".[0-9]* 2>/dev/null | head -n1`
            if [ ! -f "$usrlibdir/$sover" ]
            then
                # We want the full path in this case
                sover=`ls "$libdir/$solib.so".[0-9]* 2>/dev/null | head -n1`
                [ -f "$sover" ] || sover=""
            fi

            if [ -z "$sover" ]
            then
                error "Could not find the ...$libdir/$sodev.so symlink target"
                rc=2
            # Use -f because $sodev.so may be a broken symlink
            elif ! dry_run ln -s -f "$sover" "$usrlibdir/$sodev.so"
            then
                error "Could not create the ...$libdir/$sodev.so symlink"
                rc=2
            elif [ $rc -eq 0 ]
            then
                rc=1
            fi
        fi
    done
    if [ $rc -eq 2 -a -n "$wt_create_so_warn" ]
    then
        wt_create_so_warn=
        warning "The symlink creation will fail if the non-dev package is not installed."
        [ -n "$opt_dry_run" ] && warning "This is particularly likely with --dry-run."
    fi
    return $rc
}

# wt_create_sos <pkgdev> <sodev1> ...
#
# Create the development library symlinks in the <sodev1> ... list using
# wt_create_so(). If they all succeeded, remove <pkgdev> from the broken and
# missing packages lists.
wt_create_sos()
{
    local lib success
    local pkg="$1"
    shift

    fixed=""
    for lib in "$@"
    do
        wt_create_so "$lib"
        # Only mark a package as fixed if no error occurred and at least one
        # symlink was provided (if no symlink was provided the package is
        # presumably bad for other reasons).
        rc=$?
        [ $rc -eq 2 ] && fixed=0
        [ $rc -eq 1 -a -z "$fixed" ] && fixed=1
    done
    if [ "$fixed" = "1" ]
    then
        pkgworkaround="$pkgworkaround "`wt_get_bad_pkgs "$pkg"`
        wt_remove_bad_pkg "$pkg"
    fi
}


#####
#
# Debian
#
#####

#
# Debian: Package helpers
#

# apt_check <action> <pkg> <grep-args>
#
# Checks that the information about <pkg> matches the specified <grep-args>.
# With the 'show' <action> this can be used that the package actually exists,
# has the expected version, etc.
apt_check()
{
    local action="$1"
    local pkg="$2"
    shift 2
    LANG= apt-cache "$action" "$pkg" 2>/dev/null | egrep -q "$@"
}

# apt_pkg [--test] <pkg1> ...
#
# If <pkg1> exists, schedule it for installation and return success.
# Otherwise try again with the next package in the list.
#
# If none of the packages exist and --test was not specified, add them all
# to the missing packages list and return failure.
apt_pkg()
{
    local pkg pkgarch
    local test=
    if [ "$1" = "--test" ]
    then
        test=1
        shift
    fi

    echo -n "Checking $*..."
    for pkgarch in $*
    do
        pkg=`echo "$pkgarch" | sed -e "s/:.*//g"`
        if apt_check show "$pkgarch" "Package: $pkg"
        then
            echo " yes"
            pkginstall="$pkginstall $pkgarch"
            return 0
        fi
    done
    echo " missing"
    [ -z "$test" ] && pkgmissing="$pkgmissing "`echo "$@" | sed -e 's/ /|/g'`
    return 1
}

# apt_multi [--test|--if-0 <rc>|--if-not-0 <rc>] <pkg1> ...
#
# Schedules installation of both the 32- and 64-bit versions of the package
# if possible. Otherwise installs the 64-bit version and marks the 32-bit one
# as broken.
#
# Specifically, if --if-0 (resp. --if-not-0) is specified and <rc> is not 0
# (resp. is 0), assume the package does not support multiarch.
#
# If <pkg1> exists:
# - If it supports multiarch schedule the installation of both 32- and 64-bit
#   versions and return success.
# - If it is architecture neutral schedule installation and return success.
# - Otherwise schedule installation of the native package, mark the 32-bit
#   version as broken and return failure.
#
# If <pkg1> does not exist, try again with the next package in the list.
# If none of the packages exists and --test was not specified, add them all
# to the missing packages list and return failure.
apt_multi()
{
    local pkg
    local test=
    local not_multi=
    if [ "$1" = "--test" ]
    then
        test=1
        shift
    elif [ "$1" = "--if-0" ]
    then
        [ "$2" = "0" ] || not_multi=1
        shift 2
    elif [ "$1" = "--if-not-0" ]
    then
        [ "$2" != "0" ] || not_multi=1
        shift 2
    fi

    for pkg in $*
    do
        echo -n "Checking multiarch $pkg..."
        if [ -z "$not_multi" ] && apt_check show "$pkg" "Multi-Arch: same"
        then
            echo " yes"
            pkginstall="$pkginstall $pkg:amd64 $pkg:i386"
            return 0
        elif apt_check show "$pkg" "Architecture: all"
        then
            echo " all"
            pkginstall="$pkginstall $pkg"
            return 0
        elif apt_check show "$pkg" "Package: $pkg"
        then
            echo " broken"
            pkginstall="$pkginstall $pkg"
            [ -z "$test" ] && pkgbroken="$pkgbroken $pkg:i386"
            return 1
        fi
        echo " missing"
    done
    [ -z "$test" ] && pkgmissing="$pkgmissing "`echo "$@" | sed -e 's/ /|/g'`
    return 1
}

# apt_blacklist <canary> <version> <pkgdev> <pkglibs>
#
# This is meant to deal with cases where multiarch support in <pkgdev> is
# broken by the <canary> package in a hard to detect way.
#
# Checks the version of the <canary> package and if it matches <version>
# installs the native <pkgdev> package and the 32-bit <pkglibs> package and
# returns failure.
# Otherwise invokes apt_multi() on <pkgdev> || <pkglibs> and returns success.
apt_blacklist()
{
    local canary="$1"
    local version="$2"
    local pkgdev="$3"
    local pkglibs="$4"

    if apt_check show "$canary" "Version: $version"
    then
        warning "Bad version for $canary, not using multiarch for $pkgdev"
        apt_pkg "$pkgdev"
        apt_pkg "$pkglibs:i386"
        pkgbroken="$pkgbroken $pkgdev:i386"
        return 1
    fi
    apt_multi "$pkgdev" || apt_multi "$pkglibs"
    return 0
}

apt_install()
{
    if [ -z "$opt_dry_run" ]
    then
        echo -n "Waiting for the dpkg lock"
        while fuser /var/lib/dpkg/lock >/dev/null 2>&1 ||
              fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1 ||
              fuser /var/run/unattended-upgrades.lock >/dev/null 2>&1
        do
            echo -n "."
            sleep 1
        done
        echo " done"
    fi
    dry_run apt install `wt_pretty_list "$pkginstall"` || exit 1
    echo
}


#
# Debian: Base Wine dependencies
#

apt_init()
{
    if [ `dpkg --print-architecture` != "amd64" ]
    then
        error "Expected a 64-bit Debian distribution"
        exit 1
    fi
    if [ -n "$opt_packages" ]
    then
        dry_run dpkg --add-architecture i386
        dry_run apt-get update
    fi
    wt_libdirs="/lib/i386-linux-gnu /lib/x86_64-linux-gnu"
}

apt_wine()
{
    apt_pkg   bison
    apt_pkg   flex
    apt_pkg   gcc
    apt_pkg   gcc-mingw-w64
    apt_pkg   gcc-multilib
    apt_pkg   git
    apt_multi libasound2-dev
    apt_multi libcapi20-dev
    apt_multi libdbus-1-dev
    apt_multi libfaudio-dev

    # The FontConfig development package can only be installed if the FreeType
    # one supports multiarch
    apt_multi libfreetype6
    apt_multi libfreetype6-dev
    apt_multi --if-0 $? libfontconfig1-dev || apt_multi libfontconfig1

    apt_multi libgl1-mesa-dev
    apt_multi libglu1-mesa-dev

    # The GPhoto2 development package can only be installed if the Exif
    # one supports multiarch
    apt_multi --test libexif-dev
    apt_multi --if-0 $? libgphoto2-dev || apt_multi libgphoto2-6

    apt_multi libgsm1-dev
    # apt_multi  libhal-dev # Libhal is obsolete and usually not available

    # The GnuTLS development package can only be installed if the idn2 one
    # one supports multiarch
    apt_multi --test libidn2-0-dev
    apt_multi --if-0 $? libgnutls28-dev || apt_multi libgnutls30

    apt_multi libjpeg62-turbo-dev libjpeg-turbo8-dev
    apt_multi libkrb5-dev
    apt_multi liblcms2-dev
    apt_multi libldap2-dev
    apt_multi libmpg123-dev
    apt_multi libncurses5-dev

    # The GStreamer development package can only be installed if the liborc
    # one supports multiarch
    apt_multi --test liborc-0.4-dev
    apt_multi --if-0 $? libgstreamer-plugins-base1.0-dev ||
        apt_multi libgstreamer-plugins-base1.0-0

    apt_multi libopenal-dev
    apt_multi libosmesa6-dev
    apt_multi libpcap0.8-dev || apt_multi libpcap0.8
    apt_multi libpng-dev libpng12-dev

    # The PulseAudio development package can only be installed if the Glib2
    # one supports multiarch
    apt_multi --test libglib2.0-dev
    apt_multi --if-0 $? libpulse-dev || apt_multi libpulse0

    # On Debian 9 libsane-dev claims to support multiarch but is broken
    apt_blacklist libsane-dev 1.0.25-4.1 libsane-dev libsane

    # On Ubuntu 18.04 libsdl2-dev depends on libmirclient-dev which breaks
    # without warning in a multiarch configuration!
    apt_blacklist libmirclient-dev 0.31.1-0ubuntu1 libsdl2-dev libsdl2-2.0-0

    # The CUPS development package can only be installed if the libtiff and
    # libcupsimage ones support multiarch
    rc=0
    apt_multi libtiff-dev libtiff5-dev || rc=1
    apt_multi --test libcupsimage2-dev libcupsimage-dev || rc=1
    apt_multi --if-0 $rc libcups2-dev || apt_multi libcups2

    apt_multi libudev-dev
    apt_pkg   libunwind-dev # Wine only needs the 64-bit library
    apt_multi libusb-1.0-0-dev
    apt_multi libv4l-dev
    apt_multi libvkd3d-dev
    apt_multi libvulkan-dev
    apt_multi libx11-dev
    apt_multi libxcb1-dev
    apt_multi libxcomposite-dev
    apt_multi libxcursor-dev
    apt_multi libxi-dev
    apt_multi libxinerama-dev

    # The XML and XSLT development packages can only be installed if the ICU
    # one supports multiarch
    apt_multi --test libicu-dev; rc=$?
    apt_multi --if-0 $rc libxml2-dev || apt_multi libxml2
    apt_multi --if-0 $rc libxslt1-dev || apt_multi libxslt1.1

    apt_multi  libxrandr-dev
    apt_multi  libxrender-dev
    apt_multi  libxxf86vm-dev
    apt_pkg    make
    apt_multi  ocl-icd-opencl-dev
    apt_multi  oss4-dev
    apt_pkg    prelink

    # For libnetapi
    apt_check depends samba-libs:i386 'Depends: python3?-talloc:i386'
    apt_multi --if-not-0 $? samba-dev

    apt_multi unixodbc-dev || apt_multi libodbc1
}

apt_wine_extra()
{
    apt_pkg autoconf
    apt_pkg python3   # For make_vulkan
    apt_pkg unzip     # For make_unicode
    apt_pkg wget      # For make_unicode, make_opengl
}

apt_wine_tests()
{
    # GStreamer plugins for the quartz (winegstreamer) tests
    apt_multi gstreamer1.0-libav

    apt_multi --test libmjpegutils-2.1-0
    apt_multi --if-0 $? gstreamer1.0-plugins-bad

    apt_multi gstreamer1.0-plugins-base
    apt_multi gstreamer1.0-plugins-good

    apt_multi --test libsidplay1v5
    apt_multi --if-0 $? gstreamer1.0-plugins-ugly

    apt_pkg ttf-mscorefonts-installer
    apt_pkg winbind   # For ntlm_auth
}

apt_wt_daily()
{
    apt_pkg ntfs-3g
    apt_pkg time
}

apt_workarounds()
{
    local xsltconfig
    # Work around the missing or broken multiarch support where possible

    # Needed for Debian 10
    wt_create_sos libsdl2-dev libSDL2-2.0 # Broken up to 2.0.9
    wt_create_so libSDL2 libSDL2-2.0

    # Needed for Ubuntu 18.04
    wt_create_sos libcups2-dev libcups
    wt_create_sos libfontconfig1-dev libfontconfig
    wt_create_sos libfreetype6-dev libfreetype
    wt_create_sos libgnutls28-dev libgnutls
    wt_create_sos libpcap0.8-dev libpcap
    wt_create_sos libtiff-dev libtiff
    wt_create_sos libgstreamer-plugins-base1.0-dev libgstaudio-1.0 libgstbase-1.0 libgstreamer-1.0 libgstvideo-1.0

    # Ubuntu 18.04 is missing libxslt/xsltconfig.h
    xsltconfig="libxslt/xsltconfig.h"
    if [ -f "/usr/include/x86_64-linux-gnu/$xsltconfig" -a \
         ! -f "/usr/include/i386-linux-gnu/$xsltconfig" -a \
         ! -f "/usr/include/$xsltconfig" -a \
         -d "/usr/include/libxslt" ]
    then
        dry_run ln -s "../x86_64-linux-gnu/$xsltconfig" "/usr/include/$xsltconfig"
    elif [ -f "/usr/include/x86_64-linux-gnu/$xsltconfig" -a \
           -f "/usr/include/i386-linux-gnu/$xsltconfig" -a \
           -h "/usr/include/$xsltconfig" ]
    then
        echo "Removing the obsolete /usr/include/$xsltconfig symlink (was for libxslt1-dev)"
        dry_run rm "/usr/include/$xsltconfig"
    fi

    # Needed for Debian 9
    wt_create_sos libgphoto2-dev libgphoto2 libgphoto2_port
    wt_create_sos libjpeg62-turbo-dev libjpeg
    wt_create_sos libkrb5-dev libcom_err libgssapi_krb5 libk5crypto libkrb5
    wt_create_sos libpulse-dev libpulse
    wt_create_sos libsane-dev libsane
    wt_create_sos libxml2-dev libxml2
    wt_create_sos libxslt1-dev libxslt
    wt_create_sos unixodbc-dev libodbc
}

apt_epilogue()
{
    if wt_explain_bad_pkg "faudio-dev"
    then
        echo "* FAudio is only available on distributions derived from Debian 11+."
        echo
    fi
    if wt_explain_bad_pkg "libgstreamer-plugins-base1.0-dev"
    then
        echo "* GStreamer has different header files for 32- and 64-bit. Unfortunately"
        echo "  libgstreamer-plugins-base1.0-dev:i386 cannot be installed because some of its"
        echo "  dependencies do not support multiarch. But this issue has been fixed in"
        echo "  Debian 10 which may provide a viable workaround."
        echo
    fi
    if [ -n "$opt_packages" ]
    then
        echo "* HAL is known not to be available but is obsolete anyway."
        echo
    fi
    if wt_explain_bad_pkg "ttf-mscorefonts-installer"
    then
        echo "* ttf-mscorefonts-installer is in the contrib section of the repository. You"
        echo "  may need to update /etc/apt/sources.list (man sources.list)."
        echo
    fi
    if wt_explain_bad_pkg "oss4-dev"
    then
        echo "* OSS4 is no longer available in Debian 11 but is obsolete anyway."
        echo
    fi
    if wt_explain_bad_pkg "samba-dev:i386"
    then
        echo "* samba-dev ostensibly supports multiarch but the 32-bit version depends"
        echo "  on python:i386 through python-talloc and samba-libs. Similarly the 64-bit"
        echo "  version depends on python:amd64 thus breaking multiarch support."
        echo
    fi
    if wt_explain_bad_pkg "vkd3d-dev"
    then
        echo "* vkd3d is only available on on distributions derived from Debian 10+."
        echo
    fi
}


#####
#
# Zypper package manager (openSUSE, etc.)
#
#####

#
# zypper: Package helpers
#

zypper_packages=""

zypper_pkg()
{
    local pkgarch
    if [ -z "$zypper_packages" ]
    then
        echo "Grabbing the available package list..."
        zypper_packages=`zypper packages | cut -d'|' -f3 | sort -u`
        if [ -z "$zypper_packages" ]
        then
            error "'zypper packages' did not return the list of available packages"
            exit 1
        fi
    fi

    echo -n "Checking $*..."
    for pkgarch in $*
    do
        case "$zypper_packages" in
        *" $pkgarch "*)
             echo " yes"
             pkginstall="$pkginstall $pkgarch"
             return 0
             ;;
        esac
    done
    echo " no"
    pkgmissing="$pkgmissing "`echo "$@" | sed -e 's/ /|/g'`
    return 1
}

zypper_multi()
{
    local pkg rc
    for pkg in $*
    do
        rc=0
        zypper_pkg "$pkg" || rc=1
        zypper_pkg "$pkg-32bit" || rc=1
        [ $rc -eq 0 ] && return 0
    done
    return 1
}

zypper_install()
{
    dry_run zypper install `wt_pretty_list $pkginstall` || exit 1
    echo
}


#
# zypper: Wine dependencies
#

zypper_init()
{
    if [ `arch` != "x86_64" ]
    then
        error "Expected a 64-bit openSUSE distribution"
        exit 1
    fi
    wt_libdirs="/lib /lib64"
}

zypper_wine()
{
    # Tools
    zypper_pkg   bison
    zypper_pkg   flex
    zypper_multi gcc
    zypper_pkg   git
    zypper_pkg   make
    zypper_pkg   prelink

    # Libraries
    zypper_multi alsa-devel
    zypper_multi capi4linux-devel
    zypper_multi cups-devel
    zypper_multi dbus-1-devel
    zypper_multi FAudio-devel
    zypper_multi fontconfig-devel
    zypper_multi fontconfig # Missing dependency in -devel-32bit

    zypper_multi freetype2-devel
    zypper_multi glibc-devel
    zypper_multi glu-devel

    # Installing the 32-bit glib2-devel allows working around
    # the missing gstreamer-devel-32bit package.
    zypper_multi gstreamer-devel || zypper_multi glib2-devel
    zypper_multi gstreamer-plugins-base-devel

    zypper_multi krb5-devel
    zypper_multi libcom_err-devel
    zypper_multi libexif-devel
    zypper_multi libgnutls-devel

    zypper_multi libgphoto2-devel
    zypper_multi libgphoto2-6 # Missing dependency in -devel-32bit

    zypper_multi libgsm-devel
    zypper_multi libjpeg8-devel
    zypper_multi liblcms2-devel

    zypper_multi libnetapi-devel
    zypper_multi libnetapi0 # Workaround the missing -devel-32bit package

    zypper_multi libOSMesa-devel
    zypper_multi libpcap-devel
    zypper_multi libpng16-compat-devel

    zypper_multi libpulse-devel
    zypper_multi libpulse0 # Missing dependency in -devel-32bit

    zypper_multi libSDL2-devel
    zypper_multi libtiff-devel

    zypper_pkg   libunwind-devel # Wine only needs the 64-bit library

    zypper_multi libudev-devel
    zypper_multi libusb-1_0-devel

    zypper_multi libv4l-devel
    zypper_multi libv4l2-0 # Missing dependency in -devel-32bit

    zypper_multi libX11-devel
    zypper_multi libXcomposite-devel
    zypper_multi libXcursor-devel
    zypper_multi libXext-devel
    zypper_multi libXfixes-devel
    zypper_multi libXi-devel
    zypper_multi libXinerama-devel
    zypper_multi libXxf86vm-devel
    zypper_multi libxml2-devel
    zypper_multi libXrandr-devel
    zypper_multi libXrender-devel
    zypper_multi libxslt-devel

    zypper_multi Mesa-libGL-devel
    zypper_multi Mesa-libGL1 # Workaround for the missing -devel-32bit package

    zypper_multi mpg123-devel
    zypper_multi ncurses-devel

    zypper_pkg   opencl-headers
    zypper_multi ocl-icd-devel
    zypper_multi libOpenCL1 # For the epilogue diagnostic

    zypper_multi openal-soft-devel
    zypper_multi libopenal1 # Missing dependency in -devel-32bit

    zypper_multi openldap2-devel

    zypper_multi sane-backends-devel
    zypper_multi sane-backends # Missing dependency in -devel-32bit

    zypper_multi unixODBC-devel
    zypper_multi unixODBC

    zypper_multi vkd3d-devel
    zypper_multi vulkan-devel
    zypper_multi libvulkan1 # Missing dependency in -devel-32bit

    zypper_multi zlib-devel
}

zypper_wine_extra()
{
    zypper_pkg autoconf
    zypper_pkg python3   # For make_vulkan
    zypper_pkg unzip     # For make_unicode
    zypper_pkg wget      # For make_unicode, make_opengl
}

zypper_wine_tests()
{
    zypper_pkg fetchmsttfonts

    # GStreamer plugins for the quartz (winegstreamer) tests
    zypper_multi gstreamer-plugins-bad
    zypper_multi gstreamer-plugins-base
    zypper_multi gstreamer-plugins-good
    zypper_multi gstreamer-plugins-libav
    zypper_multi gstreamer-plugins-ugly

    zypper_pkg samba-winbind   # For ntlm_auth
}

zypper_wt_daily()
{
    zypper_pkg ntfs-3g
    zypper_pkg time
}

zypper_workarounds()
{
    # Work around the missing 32-bit development packages where possible

    # Needed for openSUSE Leap 15.1
    wt_create_sos gstreamer-devel-32bit libgstbase-1.0 libgstreamer-1.0
    wt_create_sos libnetapi-devel-32bit libnetapi
    wt_create_sos Mesa-libGL-devel-32bit libGL
}

zypper_epilogue()
{
    if wt_explain_bad_pkg "FAudio-devel"
    then
        echo "* FAudio-devel is only available on openSUSE Tumbleweed."
        echo "  https://build.opensuse.org/package/show/openSUSE%3AFactory/FAudio"
        echo
    fi
    if wt_explain_bad_pkg "gstreamer-devel-32bit"
    then
        echo "* GStreamer has different header files for 32- and 64-bit. Unfortunately"
        echo "  gstreamer-devel-32bit is missing which means there is no easy workaround."
        echo "  But you can check these two pages for more information on how to manually"
        echo "  overcome this hurdle:"
        echo "  https://bugzilla.opensuse.org/show_bug.cgi?id=973217"
        echo "  https://wiki.winehq.org/OpenSUSE#Build_Tools_and_Dependencies"
        echo
    fi
    if [ -n "$opt_packages" ]
    then
        echo "* HAL and OSS4 are known not to be available but are obsolete anyway."
        echo

        echo "* The MinGW compiler is not available and there is no clear workaround."
        echo
    fi
    if wt_explain_bad_pkg "ocl-icd-devel-32bit"
    then
        if wt_explain_bad_pkg "libOpenCL1-32bit"
        then
            echo "* Both ocl-icd-devel-32bit and libOpenCL1-32bit are missing so there is no"
            echo "  OpenCL 32-bit support at all."
            echo
        else
            echo "* Update the script to work around the missing development package."
            echo
        fi
    fi
    if wt_explain_bad_pkg "prelink"
    then
        echo "* It may be possible to use the RHEL prelink package."
        echo "  https://software.opensuse.org/package/prelink"
        echo
    fi
    if wt_explain_bad_pkg "vkd3d-devel"
    then
        echo "* vkd3d is only available on openSUSE Tumbleweed."
        echo
    fi
}


#####
#
# Command line processing
#
#####

wt_parse_cmdline()
{
    local arg
    local usage=""
    while [ $# -gt 0 ]
    do
        arg="$1"
        shift
        case "$arg" in
        --wine)       opt_wine="1" ;;
        --no-wine)    opt_wine="0" ;;
        --extra)      opt_wine_extra="1" ;;
        --no-extra)   opt_wine_extra="0" ;;
        --tests)      opt_wine_tests="1" ;;
        --no-tests)   opt_wine_tests="0" ;;
        --wt-daily)   opt_wt_daily="1" ;;
        --no-wt-daily) opt_wt_daily="0" ;;
        --all)        opt_wine="1"
                      opt_wine_extra="1"
                      opt_wine_tests="1"
                      opt_wt_daily="1"
                      ;;
        --packages)   opt_packages="1" ;;
        --workarounds) opt_workarounds="1" ;;
        --dry-run)    opt_dry_run="1" ;;
        --help|-h|-?)
            usage=0
            break
            ;;
        *)
            error "unknown option '$arg'"
            usage=2
            break
            ;;
        esac
    done

    if [ -z "$usage" ]
    then
        if [ -z "$opt_wine$opt_wine_extra$opt_wine_tests$opt_wt_daily" ]
        then
            opt_wine="1"
            opt_wine_extra="1"
            opt_wt_daily="0"
        fi
        if [ -z "$opt_packages$opt_workarounds" ]
        then
            opt_packages="1"
            opt_workarounds="1"
        fi
    fi

    if [ "$usage" = "0" ]
    then
        echo "Usage: $name0 [--no-wine] [--no-extra] [--tests] [--wt-daily] [--packages] [--workarounds] [--dry-run] [--help]"
        echo

        echo "Installs the packages needed to build the 32- and 64-bit versions of Wine. When possible applies workarounds if installing both the 32- and 64-bit development packages is impossible. Can also install some extra packages needed by the tests and the wt-daily scripts."
        echo
        echo "Default options:"
        echo "  --wine --extra --no-tests --no-wt-daily --packages --workarounds"
        echo "Tested on:"
        echo "  Debian 9 & 10, Linux Mint 19.03, Ubuntu 18.04 & 19.10."
        echo "  openSUSE Leap 15.1."
        echo

        echo "Where:"
        echo "  --no-wine    Do not install the packages needed to compile Wine."
        echo "  --no-extra   Only install the packages needed to compile Wine, not those"
        echo "               needed to regenerate part of its source (autoconf, etc)."
        echo "  --tests      Install some packages needed to run the Wine tests."
        echo "  --wt-daily   Install the packages needed for the wt-daily scripts."
        echo "  --all        Same as --wine --extra --tests --wt-daily."
        echo "  --packages   Install the packages."
        echo "  --workarounds Apply workarounds for packages that don't support multiarch so"
        echo "               that both the 32- and 64-bit versions of Wine can be built."
        echo "  --dry-run    Only show which actions would be taken."
        echo "  --help, -h   Shows this help message."
        exit 0
    elif [ -n "$usage" ]
    then
        error "try '$name0 --help' for more information"
        exit $usage
    fi
}


#####
#
# Package installation
#
#####

wt_init()
{
    if [ -x "/usr/bin/apt-cache" -a -x "/usr/bin/apt-get" ]
    then
        wt_platform="apt"
    elif [ -x "/usr/bin/zypper" ]
    then
        wt_platform="zypper"
    else
        error "This Linux distribution is not supported."
        exit 1
    fi

    ${wt_platform}_init
    if [ -n "$opt_packages" ]
    then
        [ "$opt_wine" = "1" ] && ${wt_platform}_wine
        [ "$opt_wine_extra" = "1" ] && ${wt_platform}_wine_extra
        [ "$opt_wine_tests" = "1" ] && ${wt_platform}_wine_tests
        [ "$opt_wt_daily" = "1" ] && ${wt_platform}_wt_daily
    fi
}

wt_install()
{
    [ -n "$opt_packages" ] && ${wt_platform}_install
}

wt_post_install()
{
    [ -n "$opt_workarounds" ] && ${wt_platform}_workarounds
}

wt_epilogue()
{
    echo
    ${wt_platform}_epilogue

    pkgworkaround=`wt_pretty_list "$pkgworkaround"`
    if [ -n "$pkgworkaround" ]
    then
        echo "* Workarounds where successully applied for the following broken or missing"
        echo "  packages."
        echo "  $pkgworkaround"
        echo
    fi

    pkgbroken=`wt_pretty_list "$pkgbroken"`
    if [ -n "$pkgbroken" ]
    then
        echo "* Could not install the following packages because they do not support"
        echo "  multiarch."
        echo "  $pkgbroken"
        echo
    fi

    pkgmissing=`wt_pretty_list "$pkgmissing"`
    if [ -n "$pkgmissing" ]
    then
        echo "* Could not install the following packages because they are not available."
        echo "  $pkgmissing"
        echo
    fi
}


#####
#
# Main
#
#####

if [ -z "$WT_INSTALL_DEV_LIB" ]
then
    opt_wine=""
    opt_wine_extra=""
    opt_wine_tests=""
    opt_wt_daily=""
    opt_packages=""
    opt_workarounds=""
    wt_parse_cmdline "$@"
    wt_init
    wt_install
    wt_post_install
    wt_epilogue
fi
