#!/bin/sh
# Copyright (C) 2015 Francois Gouget
#
# Runs the specified command with the lowest possible CPU and I/O priority.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
name0=`basename "$0"`

ionice=""
if type ionice >/dev/null 2>&1
then
    ionice="ionice -c 3"
fi

# On Mac OS X a niceness of 20 also lowers the I/O and network priorities.
# On other systems it gets rounded to 19.
exec nice -n 20 $ionice "$@"
